db:
  host: clomonitor-db
  port: "5432"
  dbname: clomonitor
  user: clomonitor
  password: clomonitor
creds:
  githubTokens:
    - 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
tracker:
  concurrency: 10
